export const getCountryFlagCode = (countryName) => {
  return isoMap?.[countryName] || "xx";
};

const isoMap = {
  Andorra: "ad",
  Grenada: "gd",
  Guatemala: "gt",
  Barbados: "bb",
  Bangladesh: "bd",
  Macau: "mo",
  Ethiopia: "et",
  Mongolia: "mn",
  Nepal: "np",
  Fiji: "fj",
  Slovakia: "sk",
  India: "in",
  Germany: "de",
  "Czech Republic": "cz",
  Wales: "gb-wls",
  Norway: "no",
  Slovenia: "si",
  Kazakhstan: "kz",
  Latvia: "lv",
  Armenia: "am",
  Austria: "at",
  Bahrain: "bh",
  Jordan: "jo",
  Netherlands: "nl",
  Portugal: "pt",
  "Trinidad and Tobago": "tt",
  Uzbekistan: "uz",
  Dominica: "dm",
  Guyana: "gy",
  Italy: "it",
  Turkey: "tr",
  Albania: "al",
  Lithuania: "lt",
  Romania: "ro",
  "Faroe Islands": "fo",
  Azerbaijan: "az",
  Argentina: "ar",
  Ecuador: "ec",
  "South Korea": "kr",
  Mexico: "mx",
  Qatar: "qa",
  Scotland: "gb-sct",
  Singapore: "sg",
  "United States": "us",
  Venezuela: "ve",
  Maldives: "mv",
  Belize: "bz",
  Switzerland: "ch",
  England: "gb-eng",
  "Northern Ireland": "gb-nir",
  Finland: "fi",
  Estonia: "ee",
  Belarus: "by",
  Luxembourg: "lu",
  "Equatorial Guinea": "gq",
  Comoros: "km",
  Gabon: "ga",
  Gambia: "gm",
  "South Africa": "za",
  Mauritania: "mr",
  Egypt: "eg",
  Namibia: "na",
  Uganda: "ug",
  Pakistan: "pk",
  Cuba: "cu",
  Montserrat: "ms",
  France: "fr",
  Ukraine: "ua",
  Denmark: "dk",
  Bulgaria: "bg",
  Cyprus: "cy",
  Georgia: "ge",
  Liechtenstein: "li",
  Lebanon: "lb",
  Congo: "cg",
  Aruba: "aw",
  Jamaica: "jm",
  Sweden: "se",
  Montenegro: "me",
  Serbia: "rs",
  Kosovo: "xx",
  Malta: "mt",
  Cambodia: "kh",
  Kuwait: "kw",
  Russia: "ru",
  "Saudi Arabia": "sa",
  Iceland: "is",
  Spain: "es",
  "Bosnia and Herzegovina": "ba",
  Hungary: "hu",
  "San Marino": "sm",
  Moldova: "md",
  Colombia: "co",
  Indonesia: "id",
  Japan: "jp",
  Kenya: "ke",
  Laos: "la",
  Liberia: "lr",
  Panama: "pa",
  Poland: "pl",
  Brazil: "br",
  Botswana: "bw",
  Zambia: "zm",
  Israel: "il",
  Honduras: "hn",
  "Hong Kong": "hk",
  Belgium: "be",
  Croatia: "hr",
  Greece: "gr",
  Peru: "pe",
  "Sri Lanka": "lk",
  Cameroon: "cm",
  Togo: "tg",
  Angola: "ao",
  Bahamas: "bs",
  "Dominican Republic": "do",
  "Republic of Ireland": "ie",
  "China PR": "cn",
  Myanmar: "mm",
  Oman: "om",
  Nigeria: "ng",
  "Turks and Caicos Islands": "tc",
  Suriname: "sr",
  "El Salvador": "sv",
  Thailand: "th",
  "Guinea-Bissau": "gw",
  Nicaragua: "ni",
  Gibraltar: "gi",
  Iran: "ir",
  "United Arab Emirates": "ae",
  Madagascar: "mg",
  Malawi: "mw",
  Burundi: "bi",
  Benin: "bj",
  Seychelles: "sc",
  Canada: "ca",
  Malaysia: "my",
  Philippines: "ph",
  Vanuatu: "vu",
  Chile: "cl",
  Palestine: "ps",
  Vietnam: "vn",
  Morocco: "ma",
  "South Sudan": "ss",
  Bermuda: "bm",
  Australia: "au",
  "Timor-Leste": "tl",
  Iraq: "iq",
  Tunisia: "tn",
  Afghanistan: "af",
  Yemen: "ye",
  Syria: "sy",
  Turkmenistan: "tm",
  Bolivia: "bo",
  "Solomon Islands": "sb",
  Mauritius: "mu",
  "British Virgin Islands": "vg",
  "Cayman Islands": "ky",
  Senegal: "sn",
  Mali: "ml",
  Ghana: "gh",
  Niger: "ne",
  Libya: "ly",
  Zimbabwe: "zw",
  "Central African Republic": "cf",
  Tanzania: "tz",
  "Puerto Rico": "pr",
  Haiti: "ht",
  Algeria: "dz",
  "Costa Rica": "cr",
  Paraguay: "py",
  Eswatini: "sz",
  Mozambique: "mz",
  Lesotho: "ls",
  Tajikistan: "tj",
  Bhutan: "bt",
  Uruguay: "uy",
  Guam: "gu",
  Guinea: "gn",
  Samoa: "ws",
  "American Samoa": "as",
  Tahiti: "xx",
  "Papua New Guinea": "pg",
  "New Caledonia": "nc",
  Tonga: "to",
  Djibouti: "dj",
  Somalia: "so",
  Chad: "td",
  Eritrea: "er",
  "Sierra Leone": "sl",
  "Antigua and Barbuda": "ag",
  Rwanda: "rw",
  Sudan: "sd",
  "North Macedonia": "mk",
  Anguilla: "ai",
  "Burkina Faso": "bf",
  "São Tomé and Príncipe": "st",
  Curaçao: "cw",
  "New Zealand": "nz",
  "Cook Islands": "ck",
  "Brunei Darussalam": "bn",
};
